# Split from the original monolithic runtests.jl — included by runtests.jl (common.jl
# provides REFROOT/DATAROOT, the shared GaAs/diamond models, and helpers).
@testset "postw90.jl drop-in driver" begin
    # postw90_main dispatches the .win keywords and writes the reference-named files. The
    # oracle .dat files (committed under test/data/postw90, generated by postw90.x with the
    # committed .win) must be reproduced from the corresponding test-suite inputs.
    pd = joinpath(@__DIR__, "data", "postw90")
    function stage_pw(refdir, datadir, plain, zipped)
        tmp = mktempdir()
        for f in readdir(datadir)
            endswith(f, ".dat") || cp(joinpath(datadir, f), joinpath(tmp, f))
        end
        for f in plain
            cp(joinpath(refdir, f), joinpath(tmp, f); follow_symlinks = true)
        end
        for f in zipped
            if isfile(joinpath(refdir, f))
                cp(joinpath(refdir, f), joinpath(tmp, f); follow_symlinks = true)
            else
                run(pipeline(`bunzip2 -kc $(joinpath(refdir, f * ".bz2"))`,
                             stdout = joinpath(tmp, f)))
            end
        end
        tmp
    end
    function datdiff(ours, ref; skip = 0, rtol = 1e-6)
        la = readlines(ours)[(skip+1):end]
        lb = readlines(ref)[(skip+1):end]
        length(la) == length(lb) || return false
        for (x, y) in zip(la, lb)
            x == y && continue
            tx = tryparse.(Float64, split(x))
            ty = tryparse.(Float64, split(y))
            (length(tx) == length(ty) && !any(isnothing, tx) && !any(isnothing, ty)) ||
                return false
            all(abs(p - q) <= rtol * max(1e-30, abs(q)) + 1e-7
                for (p, q) in zip(tx, ty)) || return false
        end
        true
    end

    # kubo_S/kubo_A/jdos on Fe
    kd = joinpath(REFROOT, "testpostw90_fe_kubo_Axy")
    if isfile(joinpath(kd, "Fe.eig")) && Sys.which("bunzip2") !== nothing
        tmp = stage_pw(kd, joinpath(pd, "fe_kubo"), ("Fe.eig",), ("Fe.chk.fmt", "Fe.mmn"))
        postw90_main(joinpath(tmp, "Fe"); verbose = false)
        for f in ("Fe-kubo_A_xy.dat", "Fe-kubo_S_xx.dat", "Fe-jdos.dat")
            @test datdiff(joinpath(tmp, f), joinpath(pd, "fe_kubo", f))
        end
    else
        @test_skip false
    end

    # geninterp on silicon (G18.10 rows; line 1 is a date header on the oracle side)
    gd = joinpath(REFROOT, "testpostw90_si_geninterp")
    if isfile(joinpath(gd, "silicon.eig")) && Sys.which("bunzip2") !== nothing
        tmp = stage_pw(gd, joinpath(pd, "si_geninterp"), ("silicon.eig",),
                       ("silicon.chk.fmt", "silicon.mmn"))
        postw90_main(joinpath(tmp, "silicon"); verbose = false)
        @test datdiff(joinpath(tmp, "silicon_geninterp.dat"),
                      joinpath(pd, "si_geninterp", "silicon_geninterp_oracle.dat");
                      skip = 2, rtol = 1e-8)
    else
        @test_skip false
    end

    # dos on copper
    cd_ = joinpath(REFROOT, "testpostw90_example04_dos")
    if isfile(joinpath(cd_, "copper.eig")) && Sys.which("bunzip2") !== nothing
        tmp = stage_pw(cd_, joinpath(pd, "copper_dos"), ("copper.eig",), ("copper.chk.fmt",))
        postw90_main(joinpath(tmp, "copper"); verbose = false)
        @test datdiff(joinpath(tmp, "copper-dos.dat"),
                      joinpath(pd, "copper_dos", "copper-dos.dat"); rtol = 1e-7)
    else
        @test_skip false
    end

    # ahc-fermiscan on Fe (adaptive refinement + Fermi scan)
    fd = joinpath(REFROOT, "testpostw90_fe_ahc_adaptandfermi")
    if isfile(joinpath(fd, "Fe.eig")) && Sys.which("bunzip2") !== nothing
        tmp = stage_pw(fd, joinpath(pd, "fe_ahc_scan"), ("Fe.eig",), ("Fe.chk.fmt", "Fe.mmn"))
        postw90_main(joinpath(tmp, "Fe"); verbose = false)
        @test datdiff(joinpath(tmp, "Fe-ahc-fermiscan.dat"),
                      joinpath(pd, "fe_ahc_scan", "Fe-ahc-fermiscan.dat"); rtol = 1e-6)
    else
        @test_skip false
    end

    # w90chk2chk.jl equivalent: chk ↔ chk.fmt round-trip preserves the data exactly
    ck = joinpath(REFROOT, "testpostw90_fe_kubo_Axy")
    if isfile(joinpath(ck, "Fe.chk.fmt.bz2")) && Sys.which("bunzip2") !== nothing
        tmp = mktempdir()
        run(pipeline(`bunzip2 -kc $(joinpath(ck, "Fe.chk.fmt.bz2"))`,
                     stdout = joinpath(tmp, "Fe.chk.fmt")))
        c1 = read_chk_fmt(joinpath(tmp, "Fe.chk.fmt"))
        write_chk(joinpath(tmp, "Fe.chk"), c1)
        c2 = read_chk(joinpath(tmp, "Fe.chk"))
        @test c2.u_matrix ≈ c1.u_matrix atol = 0
        @test c2.m_matrix ≈ c1.m_matrix atol = 0
        @test c2.centres ≈ c1.centres atol = 0
    else
        @test_skip false
    end
end

@testset "ballistic transport (tran_bulk, Landauer)" begin
    # Oracle self-generated with wannier90.x on tellurium (helical chains ∥ c, 12 bands → 9
    # WFs, transport_mode = bulk along z, tran_write_ht): the assembled principal-layer
    # blocks, T(E) and DOS are committed under test/data/te_tran. The v4-dev `tran_read_ht`
    # input path segfaults upstream, so the full-pipeline oracle is the one used.
    td = joinpath(@__DIR__, "data", "te_tran")
    gd = joinpath(REFROOT, "testpostw90_te_gyrotropic")
    if isfile(joinpath(gd, "Te.mmn")) && isfile(joinpath(td, "Te_qc.dat"))
        tmp = mktempdir()
        for f in ("Te.amn", "Te.mmn", "Te.eig")
            cp(joinpath(gd, f), joinpath(tmp, f); follow_symlinks = true)
        end
        cp(joinpath(td, "Te.win"), joinpath(tmp, "Te.win"))
        model, win, res = run_wannier(joinpath(tmp, "Te"))
        energies, qc, dos = run_transport(model, win, res; seedname = joinpath(tmp, "Te"))
        # assembled blocks vs the reference _htB.dat (F12.6 file precision)
        H00r, H01r = read_ht(joinpath(td, "Te_htB.dat"))
        H00, H01 = read_ht(joinpath(tmp, "Te_htB.dat"))
        @test maximum(abs.(H00 - H00r)) < 1e-5
        @test maximum(abs.(H01 - H01r)) < 1e-5
        # conductance and DOS curves vs the reference scan
        readcurve(f) = [parse(Float64, split(ln)[2]) for ln in readlines(f)
                        if !startswith(strip(ln), "#") && length(split(ln)) == 2]
        qcr = readcurve(joinpath(td, "Te_qc.dat"))
        dosr = readcurve(joinpath(td, "Te_dos.dat"))
        @test length(qc) == length(qcr)
        @test maximum(abs.(qc .- qcr)) < 1e-5
        @test maximum(abs.(dos .- dosr)) < 1e-3      # DOS peaks are GF-singularity sensitive
    else
        @test_skip false
    end
end

@testset "Γ-only real-orthogonal parity (wann_main_gamma)" begin
    # The gamma_only pipeline route: real-orthogonal Jacobi sweeps on the half b-set, with
    # Γ-disentanglement realified for the valcond/na_chain cases. All gauges must be real.
    cases = [
        ("testw90_benzene_gamma_val", "benzene", 10.455472666, 12.958338012),
        ("testw90_benzene_gamma_valcond", "benzene", 28.959463251, 31.468492322),
        ("testw90_benzene_gamma_val_hexcell", "benzene", 9.743320252, 12.091929660),
        ("testw90_na_chain_gamma", "Na_chain", 36.511339464, 37.505387845),
    ]
    for (dir, seed, omi, omtot) in cases
        p = joinpath(REFROOT, dir, seed)
        if isfile(p * ".mmn")
            _, _, res = run_wannier(p)
            @test res.omega_I ≈ omi atol = 1e-6
            @test res.spread.Ω ≈ omtot atol = 1e-6
            @test maximum(abs.(imag.(res.U))) < 1e-10       # real gauge — real WFs
        else
            @test_skip false
        end
    end
end

